channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - dill==0.3.6
  - numpy==1.25.2
  - requests==2.31.0
  - torch==2.0.1
  - torchvision==0.15.2
  - tqdm==4.66.1
name: mlflow-env
